CONNECT 'jdbc:derby:db;create=true';
CREATE TABLE USERS_TABLE (ID INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),USERNAME VARCHAR(20),PASSWORD BLOB,SALT BLOB, CREDITS INTEGER DEFAULT 100);
exit;
